### ISSUE TITLE
please release the gem

### ISSUE THREAD

**Issue by alony** [ryu39/active_record-pg_generate_series#11]
Hi ryu39,

could you please release the gem version v0.1.3 with the changes which are already there. I have the same workaround for the "Fix undefined method 'sanitize' error in Rails 5.1.0." and would be happy to remove it with the release of active_record-pg_generate_series :)
Sorry for bothering you!

Cheers,
Alona

**Comment by ryu39** [comment]
Oh, I'm sorry got annoy you.

I released latest version [v0.1.3](https://rubygems.org/gems/active_record-pg_generate_series/versions/0.1.3) which contains #7 .
Please use this version.

**Comment by alony** [comment]
wow thanks a lot!
