### ISSUE TITLE
Typo in the repo description

### ISSUE THREAD

**Issue by To1ne** [ryu39/active_record-pg_generate_series#13]
Better change the repo description:

```diff
-Add a feature which inserts records using PostgreSQL GENERATE_SERISE function to ActiveRecord
+Add a feature which inserts records using PostgreSQL GENERATE_SERIES function to ActiveRecord
```

**Comment by ryu39** [comment]
Thank you for your comment!
I fixed  GENERATE_SERISE to  GENERATE_SERISE.
Please check the repository description.

**Comment by To1ne** [comment]
![oops](https://68.media.tumblr.com/a7893f6fd9e3039af8e0bb801477728b/tumblr_o96yct96NF1r608gvo1_500.gif)

Again a typo in your comment. But no problem issue description is good now.
